name: DEV Build and deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      IS_PROD: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        id: npm-install
        run: |
          npm install --unsafe-perm=true

      - name: Deploy
        id: npm-deploy
        run: |
          npm run deploy
